Mid: storage-mon: daemonize storage_mon to deal with I/O hangs.(Add daemon/client mode)
ClusterLabs/resource-agents pull request #1886
Opened 2023-07-23 22:05 UTC by HideoYamauchi

Hi All,

This fix is a modified version of the following PR.
 - https://github.com/ClusterLabs/resource-agents/pull/1862

This PR reflects the comments in the previous PR.

Please comment on this fix.

Best Regards,
Hideo Yamauchi.

2023-08-16 10:20 UTC, oalbrigt requested changes
I've added a couple of comments for improvements, and you have to add `BuildRequires: libqb-devel` and `Requires: libqb` to the spec-file.

2023-08-16 10:20 UTC, oalbrigt commented on heartbeat/storage-mon.in
> +OCF_RESKEY_daemonize_default=""
You should set this to false, so we can use ocf_is_true later.

2023-08-16 10:20 UTC, oalbrigt commented on heartbeat/storage-mon.in
> +<content type="string" default="" />
Should be `default="${OCF_RESKEY_daemonize_default}"`.

2023-08-16 10:20 UTC, oalbrigt commented on heartbeat/storage-mon.in
> +	if [ -z "$OCF_RESKEY_daemonize" ]; then
Should be `if ! ocf_is_true "$OCF_RESKEY_daemonize"; then`. Update other occurences as well.

2023-08-16 10:40 UTC, wenningerk commented
>add `BuildRequires: libqb-devel` and `Requires: libqb` to the spec-file.

Isn't the BuildRequires-Part already in the patch? And shouldn't the Requires-Part be automatically generated?

2023-08-16 10:53 UTC, oalbrigt commented
> > add `BuildRequires: libqb-devel` and `Requires: libqb` to the spec-file.
> 
> Isn't the BuildRequires-Part already in the patch? And shouldn't the Requires-Part be automatically generated?

Ah. I see. I was trying to build on one of the distros, and forgot to diff the spec :)

The Requires part isnt auto generated though. But will probably be present be present in most cases due to Pacemaker or deps depending on it. So adding it is only to ensure it's working if anyone is installing it without those.

2023-08-16 12:10 UTC, oalbrigt commented
> > > add `BuildRequires: libqb-devel` and `Requires: libqb` to the spec-file.
> > 
> > 
> > Isn't the BuildRequires-Part already in the patch? And shouldn't the Requires-Part be automatically generated?
> 
> Ah. I see. I was trying to build on one of the distros, and forgot to diff the spec :)
> 
> The Requires part isnt auto generated though. But will probably be present be present in most cases due to Pacemaker or deps depending on it. So adding it is only to ensure it's working if anyone is installing it without those.

Correct. The Requires is auto-generated as well, so ignore the spec-part of my review :)

2023-08-16 22:57 UTC, HideoYamauchi commented
Hi Oyvind,

Check and correct the comments for OCF_RESKEY_daemonize_default and OCF_RESKEY_daemonize.

Many thanks,
Hideo Yamauchi.

2023-08-17 07:42 UTC, oalbrigt commented
@HideoYamauchi They are correct. We should use ocf_is_true 

> Hi Oyvind,
> 
> Check and correct the comments for OCF_RESKEY_daemonize_default and OCF_RESKEY_daemonize.
> 
> Many thanks, Hideo Yamauchi.

Done.

2023-08-17 08:24 UTC, oalbrigt approved these changes

2023-09-22 10:34 UTC, merged

2023-09-22 10:34 UTC, oalbrigt commented
Thanks.

2023-09-26 06:34 UTC, HideoYamauchi commented
Hi Oyvind,

Thanks for merging this fix.

Best Regards,
Hideo Yamauchi.