ibmcloud-vpc-move-route: new resource agent
ClusterLabs/resource-agents pull request #2002
Opened 2024-12-16 17:38 UTC by gampel

* ibmcloud-vpc-move-route: new resource agent
This new resource agent adds functionality to manage VIP using
IBMCloud VPC Custom Route API

2025-01-06 13:37 UTC, oalbrigt requested changes
I've added some suggestions for changes.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +        ocf.logger.info("Resource is already stopped")
We need to run a delete action for the IPs here, or it wont be in a stopped state after stopping.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +
You should remove the trailing new-lines. They dont make any sense when you run `pcs resource describe <resource>`, in manpages or other representations of the meta-data.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +        "ibmcloud-vpc-cr-vip",
The agent should be named "ibm-cloud-vpc-cr-vip" to follow the naming conventions of the other agents.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +        shortdesc="Manages moving move a IBM Cloud VIP based on Custom Route",
Double moving/move here.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +        shortdesc="Ip address for secound instance.",
Should be "second" on both desc-lines.

2025-01-06 13:37 UTC, oalbrigt commented on heartbeat/ibmcloud-vpc-cr-vip.in
> +    agent.add_action("stop", timeout=450, handler=stop_action)
start/stop timeouts can probably be much lower. It's usually 30s or lower for the start-action (60s is a usual high value if the start-action is slow), and 30s or lower for the stop- and monitor-actions.

See example at
https://github.com/ClusterLabs/resource-agents/blob/main/doc/dev-guides/ra-dev-guide.asc#metadata

2025-01-06 16:16 UTC, gampel commented
thanks, @oalbrigt should I rename the resource file in case we rename the agent form  ibmcloud-vpc-cr-vip --> ibm-cloud-vpc-cr-vip ?

2025-01-06 16:29 UTC, oalbrigt commented
> thanks, @oalbrigt should I rename the resource file in case we rename the agent form ibmcloud-vpc-cr-vip --> ibm-cloud-vpc-cr-vip ?

Yeah. Rename the file and update BUILD_IBMCLOUD_VPC_MOVE_ROUTE to BUILD_IBM_CLOUD_VPC_MOVE_ROUTE in configure.ac and the Makefile.am files as well.

2025-01-07 14:12 UTC, oalbrigt requested changes
Just a couple of changes left.

2025-01-07 15:15 UTC, oalbrigt approved these changes

2025-01-08 09:38 UTC, oalbrigt commented
Looks good to me.

I'll leave the PR open a week or so to allow others to review it before merging.

2025-01-08 18:06 UTC, gampel commented
thanks for all the help @oalbrigt

2025-01-14 08:18 UTC, merged

2025-01-14 08:18 UTC, oalbrigt commented
Thanks.